# Generated by Django 4.1.5 on 2023-01-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
